fix(tx-signing): allow signing of unsigned jwt payloads when no priva…
hirosystems/connect pull request #214
Opened 2022-04-25 13:35 UTC by kyranjamie

As discussed with @janniks, this PR modifies the existing Connect helper methods in a way that should also allow transactions to be initiated when an app has requested accounts details with `stx_requestAccounts`, rather than traditional Stacks auth.

2022-04-26 11:01 UTC, janniks requested changes

2022-04-26 11:01 UTC, janniks commented on packages/connect/src/transactions/index.ts
> +  return createUnsignedPayload(payload);
` as any` here☝️
> GitHub doesn't allow creating suggestion on deleted line 😞

2022-04-26 11:01 UTC, janniks commented on packages/connect/src/transactions/index.ts
> +  } as any;
Do we need these casts (occurs one more time below). Ideally, we allow `createUnsignedPayload` to accept the necessary types or cast to `TransactionPayload`. Also, we can move casts to the latest point which they are needed at — _e.g. see below_
```suggestion
  };
```

2022-04-26 11:24 UTC, kyranjamie commented on packages/connect/src/transactions/index.ts
> +  return createUnsecuredToken(payload as unknown as Json);
whoops

2022-04-26 12:06 UTC, kyranjamie commented on packages/connect/src/transactions/index.ts
> +  } as any;
Will need to investigate this further. The lazy `as any` is because there's no `publicKey` which is required, even though in practice it seems to work. Will check wallet code to see behaviour, which I suspect is that we default to using the key of the account you're signing with.

2022-05-20 11:42 UTC, janniks approved these changes
👍🏻

2022-05-20 11:44 UTC, kyranjamie commented
This doesn't completely fix the issue for message signing, but I don't see any reason we can't merge those changes later

2022-05-20 11:44 UTC, merged