refactor: sighash types to match btckit api
hirosystems/connect pull request #332
Opened 2023-07-26 19:44 UTC by fbwoolf

This PR refactors the `signPsbt` api `allowedSighash` types to be inclusive of all possible.

Ref changes in btckit: [refactor/sighash-types](https://github.com/btckit-org/btckit/pull/6)

2023-07-27 17:27 UTC, janniks requested changes

2023-07-27 17:27 UTC, janniks commented on packages/connect/src/types/bitcoin.ts
> +type SignatureHashLiteral = `${SignatureHash}`;
![Screenshot 2023-07-27 at 19 26 32](https://github.com/hirosystems/connect/assets/6362150/90e2c369-97d6-4fa0-b3ce-fd5a52f00e5b)

Is the intention to be able to use the key of the enum here?

2023-07-27 17:45 UTC, fbwoolf commented on packages/connect/src/types/bitcoin.ts
> +type SignatureHashLiteral = `${SignatureHash}`;
@kyranjamie that was the intention here, correct? The same in btckit: https://github.com/btckit-org/btckit/pull/6

2023-07-31 15:14 UTC, fbwoolf commented on packages/connect/src/types/bitcoin.ts
> +type SignatureHashLiteral = `${SignatureHash}`;
Np, I'll remove here too.

2023-08-01 13:43 UTC, fbwoolf commented
> Any reason not to just import & export from btckit Fara?

Not really, I can close this? Was just trying to provide parity for apps using this api.

2023-08-28 15:29 UTC, janniks commented
Not sure I follow, should we close?

2023-08-28 17:39 UTC, closed without merging